### ISSUE TITLE
Configure logrotate for mongodb.log

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#222]
mongodb.log files need to be rotated by using logrotate and that should be part of [mongodb-formula](https://github.com/mitodl/mongodb-formula)

**Comment by markbreedlove** [comment]
The PR is merged and I've run the state against QA with success. I notice that the existing production servers have their logs rotating already. I'm closing this because it seems sufficiently handled. The state can be run on production just for kicks after the `production` tag of `salt-ops` is updated.
