### ISSUE TITLE
Backup features

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#260]
To improve our existing backup process for mitx-rp, it would be helpful to do the following:

- Add a slack notification on successful completion of backups. Currently, we only get notified if backups fail, but it would be helpful to get notified that they succeeded and are actually running.
- Setup a persistent AWS EBS volume that the backup instance mounts on creation and is used to store duplicity's archive data. Duplicity requires this data and if it does not find it, it'll have to download it from remote source everytime the backup instance is created.

**Comment by blarghmatey** [comment]
While going through the current state of the backup orchestration I noticed that there are a number of `state.single` calls. I think that it might be easier to maintain and reason about if we group those into pre and post state files under the `backups` module here: https://github.com/mitodl/salt-ops/tree/master/salt/backups

Then we can use the `salt.state` function to call those SLS files with proper targeting, rather than trying to nest 3 levels of abstraction into a single function call. For instance, this section:
```salt
format_backup_drive:
  salt.function:
    - tgt: 'G@roles:backups and G@environment:{{ ENVIRONMENT }}'
    - tgt_type: compound
    - name: state.single
    - arg:
        - blockdev.formatted
    - kwarg:
        name: /dev/xvdb
        fs_type: ext4
    - require:
        - salt: create_attach_backup_volume

mount_backup_drive:
  salt.function:
    - tgt: 'G@roles:backups and G@environment:{{ ENVIRONMENT }}'
    - tgt_type: compound
    - name: state.single
    - arg:
        - mount.mounted
    - kwarg:
        name: /backups
        device: /dev/xvdb
        fstype: ext4
        mkmnt: True
        opts: 'relatime,user'

create_backup_directory:
  salt.function:
    - tgt: 'G@roles:backups and G@environment:{{ ENVIRONMENT }}'
    - tgt_type: compound
    - name: state.single
    - arg:
        - file.directory
    - kwargs:
        name: /backups/tmp
        makedirs: True
```
could be encapsulated in a single state file (e.g. `backups.prepare_disk` or `backups.mount_drive`) and then the orchestrate call could be:
```
mount_and_format_backup_drive:
  salt.state:
    - tgt: foo
    - sls:
      - backups.mount_drive
```
