### ISSUE TITLE
Ficus: email tab is missing from instructor dashboard

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#309]
On the Instructor Dashboard page, the font and layout is a bit different from what is currently in production. The email tab is missing from the Instructor Dashboard.
- Current Instructor Dashboard:
![current instructor page](https://cloud.githubusercontent.com/assets/8322892/26506780/af6b25d8-421b-11e7-94d8-3364c344e5d1.png)
https://lms.mitx.mit.edu/courses/MITx/Welcome_to_MITx/Training/instructor#view-course_info

- QA Instructor Dashboard:
![qa instructor page](https://cloud.githubusercontent.com/assets/8322892/26506782/b3da46b2-421b-11e7-95c4-ac5999d1be5c.png)
https://mitx-qa-next.mitx.mit.edu/courses/MITx/Welcome_to_MITx/Training/instructor#view-course_info

**Comment by pdpinch** [comment]
I think the missing email tag must be a configuration issue of some kind. @mitodl/devops are there any flags that need to be set with relation to course staff access to email?

**Comment by blarghmatey** [comment]
@pdpinch @NotoriousMKD the reason for the missing email tab is due to the fact that the bulk email feature flag has been moved to the database, requiring it to be controlled via the Django Admin. (https://mitx-qa-next.mitx.mit.edu/admin/bulk_email/). There is a global feature flag that enables the capability and then an additional per-course flag that is needed to enable the email tab for the given course (https://mitx-qa-next.mitx.mit.edu/admin/bulk_email/courseauthorization/add/).
