### ISSUE TITLE
Deploy new FluentD aggregators & make some config changes

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#431]
Fluentd has released v1.0.0 and we should do the following:
- Deploy a new set of instances
- Add file buffering

**Comment by pdpinch** [comment]
Does Fluentd 1.0.0 work with a shared secret, or is PKI necessary?

**Comment by pdpinch** [comment]
@shaidar ^^

**Comment by shaidar** [comment]
Waiting on [Issue#20](https://github.com/mitodl/salt-ops/issues/20)

**Comment by blarghmatey** [comment]
@pdpinch it requires a validated TLS certificate and no longer works with a shared secret.

**Comment by markbreedlove** [comment]
Adding myself as a co-asignee because Tobais suggested I help with this.

**Comment by markbreedlove** [comment]
With the following directive in the FluentD configuration:
```
<source >
  @id heroku_logs_inbound
  @type heroku_syslog_http
  port 9000
  bind 0.0.0.0
  format none
</source>
```
... I'm observing the following error trying to start FluentD:

```
Nov 22 14:59:19 ip-10-1-2-18 fluentd.sh[14133]: /var/lib/gems/2.3.0/gems/fluent-plugin-heroku-syslog-0.1.1/lib/fluent/plugin/in_heroku_syslog_http.rb:5:in `<module:Fluent>': uninitialized constant Fluent::HttpInput (NameError)
```

The file in question, `fluent/plugin/in_heroku_syslog_http.rb`, has the following contents, abridged here for clarity:
```
require 'fluent/plugin/in_http'
require_relative 'logplex'

module Fluent
  class HerokuSyslogHttpInput < HttpInput
  # ...
  end
end
```

I can replicate the error in Ruby as follows (placing `logplex.rb` in my path so that its inclusion works):
```
admin@ip-10-1-3-81:~$ irb
irb(main):001:0>
irb(main):002:0* require 'fluent/plugin/in_http'
=> true
irb(main):003:0> require_relative 'logplex'
=> true
irb(main):004:0>
irb(main):005:0* module Fluent
irb(main):006:1>   class HerokuSyslogHttpInput < HttpInput
irb(main):007:2>   end
irb(main):008:1> end
NameError: uninitialized constant Fluent::HttpInput
        from (irb):6:in `<module:Fluent>'
        from (irb):5
        from /usr/bin/irb:11:in `<main>'
irb(main):009:0>
```

The plugin repo: https://github.com/drivy/fluent-plugin-heroku-syslog-http

The plugin's gemspec claims compatibility with FluentD 1.x, but I'm doubtful because they haven't updated their usage example with 1.x-compatible syntax (e.g. `@type` instead of `type`) so I'm not sure if it's really compatible.

**Comment by markbreedlove** [comment]
The error above was with FluentD 1.1.1, but I've recently merged https://github.com/mitodl/salt-ops/pull/539, which installs 1.7.4, so this error has gone away.

**Comment by markbreedlove** [comment]
I'm working on this now:

```
Nov 22 17:24:44 <host> fluentd.sh[4975]: 2019-11-22 17:24:44 +0000 [error]: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="Other 's3' plugin already use same buffer path: type = s3, buffer path = /opt/logs/fluentd/residential/tracking"
```

**Comment by markbreedlove** [comment]
FluentD version 1.7.4 is now running in QA.

**Comment by markbreedlove** [comment]
Next: deploy in production
