### ISSUE TITLE
Ginkgo: Use Shibboleth auth to integrate directly with Touchstone

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#479]
The CAS server has been causing us a number of problems ( #408 #409 #410 ), in addition to needing an OS and django upgrade. Since we don't use CAS to authenticate any services besides Touchstone with edX, it would be simpler to integrate directly with Touchstone via Shibboleth instead. 

We should be able to use the (relatively new) 3rd party auth functionality in edX.

**Comment by shaidar** [comment]
Closing this issue as I was not able to get this to work with the Ginkgo release. The issue was that the response was being receiving on port 8000 shown below:
<img width="562" alt="screen shot 2017-11-15 at 11 49 28 pm" src="https://user-images.githubusercontent.com/1447295/33565535-5f027800-d8eb-11e7-9f72-f03740b5f4fc.png">

After looking at the code, it appears that Django versions prior to 1.9 use a method called `HttpRequest.get_host()` which ends up appending the `8000` port number and even after trying to add headers to nginx we were not successful in getting it working. 
Django versions 1.9 and above have a new method called [`HttpRequest.get_port()`](https://docs.djangoproject.com/en/1.9/ref/request-response/) which should help resolve the problem and the next release of openedx should be supporting Django 1.11.
Will close this issue for now in the hopes of reopening it with the new release of edx - `Hawthorne`
