### ISSUE TITLE
Hawthorn: use Cloudfront CDN

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#520]
edX has been making great strides in using a CDN to deliver static files (both application static files and course static files). Using a CDN should improve load times and user experience, even compared to files served directly by nginx. 

Making this change will also make #519 easier to swallow.

**Comment by blarghmatey** [comment]
I configured the CDN but there is some weirdness with how the static URLs are being generated that appears to conflict with our override of the nginx template for loading course assets from disk. I will be digging in further to see if we still need to customize that nginx location now that we are not preventing git imports from importing static assets.

**Comment by blarghmatey** [comment]
There is a bug in the edx platform that results in the font files for paragon components having an extra level to their path that doesn't exist in the on-disk directory structure. I worked around this manually by creating the extra path and copying the files there. Now there is an issue with CORS requests for the fontawesome fonts.

Besides that, the only other work remaining on this issue is to create additional cloudfront distributions for current-residential and production residential, then parameterize the pillar data accordingly.

**Comment by blarghmatey** [comment]
This is resolved, aside from the edX bug causing the fonts to load from the nested directory.
