### ISSUE TITLE
Create OCW mirror server

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#651]
Create an EC2 instance that is a replica of the ocwmirror server that is running in the W91 co-location facility.

**Comment by pdpinch** [comment]
I want to check with @JoeMartis to see if this is necessary before moving OCWCMS prod to AWS

**Comment by JoeMartis** [comment]
I don’t see a need to move the mirror server unless we have hardware, space, or access concerns.

I know we are constantly juggling files to allow the mirror to run – would this be resolved by moving to AWS?

**Comment by markbreedlove** [comment]
Status update:

This is mostly ready, but we've put it on hold because the final test is to have OCW migrated over to AWS so that the Akamai CDN at ocw.mit.edu is pointed at the AWS production origin server. The mirror scripts try to grab files from ocw.mit.edu and rely on various redirects and other resources (cloud files) that are configured there.

We'll resolve this issue after the migration is done.

**Comment by blarghmatey** [comment]
I would argue that this is complete. The mirror service is not fully functional yet, but the server is present and in use.

**Comment by markbreedlove** [comment]
That sounds right. It's also known that the mirror server wasn't functioning properly in the legacy environment anyway.
