### ISSUE TITLE
Configuring metric and log collection for OCW CMS and DB instances

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#654]
In order to be able to keep on top of issues for OCW before they become a bigger problem we should set them up with fluentd and (possibly) datadog or elastic beats.

**Comment by pdpinch** [comment]
Is this being worked on now?

Does this block our move of OCW to AWS?

**Comment by pdpinch** [comment]
Ok. I'm taking it out of this sprint. Feel free to move it back if/when you're working on it.

**Comment by markbreedlove** [comment]
@blarghmatey @shaidar As long as I'm going to be modifying the match on the `ocw-cms` role in `pillar/top.sls`, does it make any sense to change https://github.com/mitodl/salt-ops/blob/89fbb465bdcd17efb9a656bef0d2f02aab655d61/pillar/top.sls#L241 so that it's not restricting the match to `environment:ocw-production`? Seems that maybe we'd want the log rotation and logging (or whatever) configured for QA as well and the existing `logrotate` seems appropriate for both environments.

**Comment by blarghmatey** [comment]
I think it makes sense to just target on `roles:ocw-cms`. At the time that targeting was initially added, we didn't have the QA hosts deployed yet (@shaidar can confirm or deny this assumption)

**Comment by markbreedlove** [comment]
@blarghmatey Would it be out of scope to add missing logrotate configurations? A [pillar](https://github.com/mitodl/salt-ops/commit/3932cb7bf69d362f13261570a4545cbbb06a7220) exists already for the CMS but there's no state applied in `salt/top.sls`, and there's nothing yet for the DB role.

**Comment by blarghmatey** [comment]
It's not required, but it doesn't hurt to include it while you're in there.
