### ISSUE TITLE
Download MITx course list from S3 to OCW origin

### ISSUE THREAD

**Issue by shaidar** [mitodl/salt-ops#758]
Scheduled task to download `mitx_feeds.json` from S3 bucket to the OCW origin server and engines instance in order for some newly written JavaScript to load and render it.

**Comment by shaidar** [comment]
@pdpinch How often should this task run to update the file on the origin server?

**Comment by pdpinch** [comment]
@markbreedlove can you update the status on this, with some links to the code that actually makes it happen?

Also, can you confirm the file name? I think it's changed a couple times.

**Comment by markbreedlove** [comment]
The file name is `edx_courses.json` and exists at `s3://open-learning-course-data/edx_courses.json`.

It is downloaded to the AWS origin servers by https://github.com/mitodl/salt-ops/blob/7936b6f6447cb4188788ee0dcd3a023ac5d7ab7d/salt/apps/ocw/pull_edx_courses_json.sls, which is run by the Salt scheduler via [this section of the apps.ocw pillar](https://github.com/mitodl/salt-ops/blob/45196b5ec046ed0f8a386590413f5ed583e7f2dd/pillar/apps/ocw.sls#L16-L23).

The file is then available at http://ocw-origin.odl.mit.edu/courses/edx_courses.json . PR #829 was merged to let this server serve this file over plain http so that we wouldn't run into problems with the old version of openssl on the legacy systems.

There are cron jobs on the legacy systems that then pull it with `curl` onto their local filesystems, on `aka-ocw` and `ocw5`.
