### ISSUE TITLE
Define node groups for infrastructure targets in Salt

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#859]
To simplify targeting of sets of instances we should define node groups that allow us to use short names for groupings of servers.

https://docs.saltstack.com/en/latest/topics/targeting/nodegroups.html

**Comment by markbreedlove** [comment]
Are there any particular groups that we need the most?

There are a number of matchers in the topfiles that are pretty eclectic, where I'm not sure what to name them. I assume that some of these should not be defined as nodegroups because they're only relevant in the topfiles; but others seem to be good candidates.

I am working on a number of groups that I know from experience would be useful on the commandline, mainly for working with OCW and the logging cluster.

**Comment by blarghmatey** [comment]
Some good candidates would be things like:
- ovs-rc
- ovs-production
- consul-servers-prod
- consul-servers-qa
- rabbit-servers-prod

Probably best if we all 3 sit down to discuss. Maybe look at bash history to see things that we target frequently.
