### ISSUE TITLE
Infrastructure Unit and Integration Testing

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#96]

**Comment by pdpinch** [comment]
@blarghmatey what needs to be done for this one?

**Comment by blarghmatey** [comment]
This requires us to determine what are the critical pieces that we need to validate on a healthy EdX instance (and other services) so that we can have confidence at run-time that everything is doing what it should be. Once we have made those determinations we will write a set of states to execute the testinfra module that I wrote against the target nodes. It will also be incorporated in our AMI build process as a way of having a fast-fail feedback cycle.
