### ISSUE TITLE
Improve reliability of log data

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#985]
We have some intermittent cases where log data can be lost which occasionally causes issues. This will become a bigger problem as we rely more on the log aggregators for routing useful information for other purposes (e.g. edX tracking logs and Mailgun event hooks).

The scope of this issue is to identify and evaluate options and determine the next steps for implementation. Some items to consider are:
- file-based buffering in FluentD to improve durability during service restarts
- How to handle inbound Nginx requests when the FluentD aggregator is down (particularly from Mailgun and Heroku)
- Implementing a persistent write-ahead log such as [Pulsar](https://pulsar.apache.org) or [Kafka](https://kafka.apache.org)
- What our overall use cases are beyond simple logging (e.g. routing to S3, windowed metrics)

**Comment by blarghmatey** [comment]
We are moving forward with deploying Pulsar to act as a persistent buffer for all inbound data and transfer between systems.

**Comment by markbreedlove** [comment]
We could also look at having FluentD create weekly indices instead of daily. This would reduce the number of shards on the cluster, and thus the number of open file descripters per instance. We should see if we can calculate how performance would differ with a smaller number of large shards versus a large number of small ones.
